#pragma once

#include <iomanip>
#include <iostream>
#include <string>
#include <sstream>
#include <cctype>
#include <limits>
#include <climits>
#include <cfloat>
#include <stdint.h>
#include <vector>
#include <algorithm>
#include <deque>
#include <list>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <cstring>
#include <sys/stat.h>
#include <fstream>
#include <numeric>
#include <map>
#include <cstdlib>
